excerpt_separator: ""
highlighter: rouge
pygments: 
markdown: kramdown
url: http://CimeM.github.io
title: Martin Cimerman
email: cim.martin@gmail.com
author: Martin
description: iOS Developer, UX Engineer, with background in Informatics and Automation, programmer, photographer, tech lover.
paginate: 6
google_analytics: UA-78067530-1

theme: jekyll-theme-cayman